# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    #increment_version_code
  end
  
  lane :screenshots do
    capture_android_screenshots
    upload_to_play_store
  end
  
  # This is not working, and I do not know why...
  desc "Build debug and test APK for screenshots"
  lane :build_for_screengrab do
    gradle(task: "clean assembleDebug assembleAndroidTest")
    capture_android_screenshots
  end
end